name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        versions:
          - python: 3.5
            django: ">=1.11,<2.0"
          - python: 3.5
            django: ">=2.0,<2.1"
          - python: 3.5
            django: ">=2.1,<2.2"
          - python: 3.5
            django: ">=2.2,<3.0"

          - python: 3.6
            django: ">=1.11,<2.0"
          - python: 3.6
            django: ">=2.0,<2.1"
          - python: 3.6
            django: ">=2.1,<2.2"
          - python: 3.6
            django: ">=2.2,<3.0"

          - python: 3.7
            django: ">=2.0,<2.1"
          - python: 3.7
            django: ">=2.1,<2.2"
          - python: 3.7
            django: ">=2.2,<3.0"
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.versions.python }}
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install "Django${{ matrix.versions.django }}"
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Run Tests
      run: coverage run manage.py test test_tinymce
    # Upload report: Linux & macOS
    - name: Upload coverage report (Unix)
      if: matrix.os != 'windows-latest'
      run: bash <(curl -s https://codecov.io/bash)
